# Generated by Django 3.2 on 2021-04-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
