# Generated by Django 3.2 on 2021-04-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_matricula_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nivel',
            new_name='periodo',
        ),
    ]
